# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker Compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/

# Here the instructions define your application as a service called "server".
# This service is built from the Dockerfile in the current directory.
# You can add other services your application may depend on here, such as a
# database or a cache. For examples, see the Awesome Compose repository:
# https://github.com/docker/awesome-compose
services:
  php:
    build:
      context: .
    networks:
      - internal
    volumes:
      - flarum-data:/flarum
      - composer-cache:/composer-cache
      - ./extensions:/flarum/extensions
      - ./flarum.config.php:/flarum/config.php
    restart: unless-stopped
  webserver:
    image: nginx:latest
    ports:
      - 8081:8081 # adminer
      - 443:443 # flarum
    networks:
      - internal
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx-ssl.conf:/etc/nginx/nginx-ssl.conf:ro
      - ./certificate.pem:/etc/nginx/certificate.pem:ro
      - ./certificate-key.pem:/etc/nginx/certificate-key.pem:ro
      - flarum-data:/flarum
    depends_on:
      - php
      - db
    restart: unless-stopped
  db:
    image: mariadb:latest
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: flarum
    networks:
      - internal
    volumes:
      - database-data:/var/lib/mysql:Z
  dbmanager:
    image: adminer:fastcgi
    restart: always
    ports:
      - 9000:9000
    networks:
      - internal
    
networks:
  internal:

volumes:
  flarum-data:
  composer-cache:
  database-data:
